Harden: Normalize shell dependency loading boilerplate
- REFER:

  https://github.com/DepoXy/sh-source-deps-template#🤞

diff --git a/lib/biblio-ssh b/lib/biblio-ssh
--- a/lib/biblio-ssh
+++ b/lib/biblio-ssh
@@ -7,20 +7,125 @@
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-_bibliossh_source_deps () {
-  local _321_root="${1:-$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")/..}"
+# *** <beg boilerplate `source_deps`: ------------------------------|
+#                                                                   |
+
+_biblio_ssh__this_filename="biblio-ssh"
+
+_biblio_ssh__source_deps () {
+  local sourced_all=true
+
+  # On Bash, user can source this file from anywhere.
+  # - If not Bash, user must `cd` to this file's parent directory first.
+  local prefix="$(dirname -- "${_biblio_ssh__this_fullpath}")"
+
+  # USAGE: Load dependencies using path relative to this file, e.g.:
+  #   _source_file "${prefix}" "../deps/path/to/lib" "dependency.sh"
+
+  #                                                                 |
+  # *** stop boilerplate> ------------------------------------------|
 
   # Load: highlight, infuse_symlink_from_home_to_paddock_unless_conflict
-  . "${_321_root}/lib/biblio.321"
+  _biblio_ssh__source_file "${prefix}" "" "biblio.321"
 
   # Load: verify_environment, verify_or_start_agent, ssh_add_key_with_passphrase.
   # - CXREF: ~/.kit/odd/321open/bin/ssh-agent-kick
-  . "${_321_root}/bin/ssh-agent-kick"
+  _biblio_ssh__source_file "${prefix}" "../bin" "ssh-agent-kick"
 
   # Load: ssh_agent_kill
   # - CXREF: ~/.kit/odd/321open/bin/ssh-agent-kill
-  . "${_321_root}/bin/ssh-agent-kill"
+  _biblio_ssh__source_file "${prefix}" "../bin" "ssh-agent-kill"
+
+  # *** <more boilerplate: -----------------------------------------|
+  #                                                                 |
+
+  ${sourced_all}
 }
+
+_biblio_ssh__smells_like_bash () { declare -p BASH_SOURCE > /dev/null 2>&1; }
+
+_biblio_ssh__print_this_fullpath () {
+  if _biblio_ssh__smells_like_bash; then
+    echo "$(realpath -- "${BASH_SOURCE[0]}")"
+  elif [ "$(basename -- "$0")" = "${_biblio_ssh__this_filename}" ]; then
+    # Assumes this script being executed, and $0 is its path.
+    echo "$(realpath -- "$0")"
+  else
+    # Assumes cwd is this script's parent directory.
+    echo "$(realpath -- "${_biblio_ssh__this_filename}")"
+  fi
+}
+
+_biblio_ssh__this_fullpath="$(_biblio_ssh__print_this_fullpath)"
+
+_biblio_ssh__shell_sourced () {
+  [ "$(realpath -- "$0")" != "${_biblio_ssh__this_fullpath}" ]
+}
+
+_biblio_ssh__source_file () {
+  local prfx="${1:-.}"
+  local depd="${2:-.}"
+  local file="${3:-.}"
+
+  local deps_dir="${prfx}/${depd}"
+  local deps_path="${deps_dir}/${file}"
+
+  # Just in case sourced file overwrites top-level `_biblio_ssh__this_filename`,
+  # cache our copy, should we need it for an error message.
+  local _this_file_name="${_biblio_ssh__this_filename}"
+
+  if [ -f "${deps_path}" ]; then
+    # SAVVY: Source files from their dirs, so they can find their deps.
+    local before_cd="$(pwd -L)"
+    cd "${deps_dir}"
+    # SAVVY: If errexit, error while sourcing kills process immediately,
+    # and error you see might indicate this source file, but the line
+    # number for the file being sourced. E.g.,
+    #   /path/to/bin/myapp: 442: export: Illegal option -f
+    # where `442` is line number from, e.g., 'deps/lib/dep.sh'.
+    if ! . "${deps_path}"; then
+      >&2 echo "ERROR: Dependency ‘${file}’ returned nonzero when sourced"
+      sourced_all=false
+    fi
+    cd "${before_cd}"
+  else
+    local depstxt=""
+    [ "${prfx}" = "." ] || depstxt="in ‘${deps_dir}’ or "
+    >&2 echo "ERROR: ‘${file}’ not found under ‘${deps_dir}’"
+    if _biblio_ssh__smells_like_bash; then
+      >&2 echo "- GAFFE: This looks like an error with the ‘_biblio_ssh__source_file’ arguments"
+    else
+      >&2 echo "- HINT: You must source ‘${_this_file_name}’ from its parent directory"
+    fi
+    sourced_all=false
+  fi
+}
+
+# BONUS: You can use these aliases instead of the uniquely-named functions,
+# just be aware not to call any alias after calling _source_deps.
+_shell_sourced () { _biblio_ssh__shell_sourced; }
+_source_deps () { _biblio_ssh__source_deps; }
+
+_biblio_ssh__source_deps_unset_cleanup () {
+  unset -v _biblio_ssh__this_filename
+  unset -f _biblio_ssh__print_this_fullpath
+  unset -f _biblio_ssh__shell_sourced
+  unset -f _shell_sourced
+  unset -f _biblio_ssh__smells_like_bash
+  unset -f _biblio_ssh__source_deps
+  unset -f _source_deps
+  unset -f _biblio_ssh__source_deps_unset_cleanup
+  unset -f _biblio_ssh__source_file
+}
+
+# USAGE: When this file is being executed, before doing stuff, call:
+#   _source_deps
+# - When this file is being sourced, call both:
+#   _source_deps
+#   _biblio_ssh__source_deps_unset_cleanup
+
+#                                                                   |
+# *** end boilerplate `source_deps`> -------------------------------|
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
@@ -195,5 +300,5 @@ remove_symlinks_paddock_ssh () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-_bibliossh_source_deps
+_source_deps
 
